#!/usr/bin/ruby
# coding: utf-8

output, state, percentage, remaining = /: (\w+), (\d+[%]), (\d+[:]\d+)/.match(`acpi -b`).to_a

return if state.nil?
return puts '' if state == 'Unknown'
return puts "#{percentage} " if state == 'Charging'
return puts "#{percentage} - #{remaining} remaining"

